#include <catch.hpp>

#include <nsearch/FASTQ/Writer.h>
#include <nsearch/PairedEnd/Merger.h>
#include <nsearch/PairedEnd/Reader.h>
#include <nsearch/Alphabet/DNA.h>

using namespace PairedEnd;

TEST_CASE( "Merger" ) {
  bool     res;
  Sequence< DNA > merged;

  SECTION( "non-staggered overlap" ) {
    Merger< DNA >   merger( 5, 1.0 );
    Sequence< DNA > fwd1 = Sequence< DNA >( "fwd1", "ACTGGATGGA", "JJJJJJJJJJ" );
    Sequence< DNA > rev1 =
      Sequence< DNA >( "rev1", "ATGGAATCCC", "JJJJJJJJJJ" ).Reverse().Complement();

    res = merger.Merge( fwd1, rev1, &merged );
    REQUIRE( res == true );
    REQUIRE( merged == Sequence< DNA >( "ACTGGATGGAATCCC" ) );
  }

  SECTION( "staggered overlap (merged sequence is trimmed)" ) {
    Merger< DNA >   merger( 5, 1.0 );
    Sequence< DNA > fwd1 = Sequence< DNA >( "fwd1", "ATCCCGGA", "JJJJJJJJ" );
    Sequence< DNA > rev1 =
      Sequence< DNA >( "rev1", "ATGGAATCCC", "JJJJJJJJJJ" ).Reverse().Complement();

    res = merger.Merge( fwd1, rev1, &merged );
    REQUIRE( res == true );
    REQUIRE( merged == Sequence< DNA >( "ATCCC" ) );
  }

  SECTION( "min bases requirement" ) {
    Merger< DNA > merger( 6, 0.8 );

    Sequence< DNA > fwd1 = Sequence< DNA >( "fwd1", "ACTGGATGGA", "JJJJJJJJJJ" );
    Sequence< DNA > rev1 =
      Sequence< DNA >( "rev1", "ATGGAATCCC", "JJJJJJJJJJ" ).Reverse().Complement();

    res = merger.Merge( fwd1, rev1, &merged );
    REQUIRE( res == false );
  }

  SECTION( "min identity requirement" ) {
    Merger< DNA > merger( 5, 1.0 );

    Sequence< DNA > fwd1 = Sequence< DNA >( "fwd1", "ACTGGATGGA", "JJJJJJJJJJ" );
    Sequence< DNA > rev1 =
      Sequence< DNA >( "rev1", "GATAGAATCCC", "JJJJJJJJJJJ" ).Reverse().Complement();

    res = merger.Merge( fwd1, rev1, &merged );
    REQUIRE( res == false );
  }

  SECTION( "posterior Q calculation" ) {
    Merger< DNA >   merger( 3, 1.0 );
    Sequence< DNA > fwd1 = Sequence< DNA >( "fwd1", "ATTGACCGT", "1>AA1@FFF" );
    Sequence< DNA > rev1 =
      Sequence< DNA >( "rev1", "ACCGTGAATC", "?AAAAFFFFF" ).Reverse().Complement();

    res = merger.Merge( fwd1, rev1, &merged );
    REQUIRE( res == true );
    REQUIRE( merged.sequence == "ATTGACCGTGAATC" );
    REQUIRE( merged.quality == "1>AAKKKKKFFFFF" );
  }
}

TEST_CASE( "Integration" ) {
  // - Nonstaggered
  // - Staggered
  // - No alignment
  const char* forwardReadsContent =
    R"(@MISEQ:1:1101:14454:2872#ATATCGTATCTTTCCC/1
CATTAGGGTTAGCCTCGGTACGGTCAGGCATCCACGGCGCTTTAAAATAGATGTTATAGATATTCAAATAACCCTGAAACAAATGCTTAGGGATTTTATTGGTATCAGGGTTAATCGTGCCAAGAAAAGCGGCATGGTCAATATAACCAGTAGTGTTAACAGTCGGGAGAGGAGTGGCATTAACACCATCCTTCATGAACTTAATCCACTGTTCACCATAAACGTGACGATGAGGGACATAAAAAGTAAA
+MISEQ:1:1101:14454:2872#ATATCGTATCTTTCCC/1
1>AA1@FFFF@1BGBGGGEFE?EFEAG0FGGHGFHFGGGGGGGHEHGHHH1DGFGHHHHHHHHHHHHHFHHHHHHHHHHHHHHHHHHFHHHHHHFHHHHHHF1FFHHHHHGGHHHHGHH/FFCGHHHHHHGGGCG0GGFHHHHFHHGFEAFFBFFHHHHGGHHHG?CCGGCCGCHFEGHHHHHHHHGHHHHFHHHHGHHHHGGGGGGFFGGGGGGGFGGGEGGGAEFG?EFEFFFFFFFFFBFFFB9BFF

@MISEQ:1:1101:16050:2871#TTGCTCGTTCTTTCCC/1
CGATGGACGGCGAGGGTCTGGATCATGACCCATTTGGAGAAGATGCGGTCCTTGGAGAACTTGTTGCCGGACATGAAATTCTTGCCATCGGCTTCCTTGGTTTCGCCCATCGAGGCGTAGCTGTGGCCCGGCTGATAGTGCAAGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGTTGCTCGTGATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAAGGTAGTTGTTGTTTTATTTCGCTGC
+MISEQ:1:1101:16050:2871#TTGCTCGTTCTTTCCC/1
>AA>A3BF?DB>2A2E2FCFBF5GFEGFHHHHHFHFHCBCCGHHHHCCAEEHGD3BGGGGEGGFHHHHGGGGGHGHFGFHHHHHHHFHHGGG/EFHHHHHBGGHGGGGGHHGGGGGG?CGGHGHC0GHHCGGGGFGGH=GFFHHHHHGGGGG.GHG@9AEGGGFGGGGFBFGGGGGGFBDDAFFBA9.:/9/;FEDBF/FBF<FEFEFFFFF?FFFF?################################

@MISEQ:1:1101:11693:2867#CGAAGTTCAACCAAAA/1
CATGGAGTTTGATCATGGCTCAGAGTGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAACGGAATTTAAAAGAGCTTGCTCTTTTAAATTTAGTGGCGCACGGGTGAGTAATATATAGCTAATCTGCCCCTTGCTGGAGGACAACAGTTAGAAATGACTGCTAATACTCCATACTCCTTTTTACCATAAGATAAATCGGGAAAGAATTTCGGCAAGGGATGAGACTATATCGTATCAGCTAGTCGGG
+MISEQ:1:1101:11693:2867#CGAAGTTCAACCAAAA/1
3A333FFBBFFFGGGGGFAGGFFFFFGEFGFG2A?EGGGAAAEHHFFDGGDFFHHHGFHEEGHGGGGGGHGHGHGGFGFHHHHHGFHHGGHFHHHGHHHGGGEGGGG>BGHHGHFFFHHHHHHHGFHHFFHHGEGHGHGHHGGGHHHGHHHHHHHHHBGHFFHGHHHFDGBDGHHHHGHHHBFBGCGHHEHGFGGGEFFG.;AB@GGGGGBBF/;?BBEFFFF?/BFFFFFFFBEFFFFFFFFFF/FDB#
)";

  const char* reverseReadsContent =
    R"(@MISEQ:1:1101:14454:2872#ATATCGTATCTTTCCC/2
TTTCTCCATTGCGTCGTGGCCTTGCTATTGACTCTACTGTAGACATTTTTACTTTTTATGTCCCTCATCGTCACGTTTATGGTGAACAGTGGATTAAGTTCATGAAGGATGGTGTTAATGCCACTCCTCTCCCGACTGTTAACACTACTGGTTATATTGACCATGCCGCTTTTCTTGGCACGATTAACCCTGATACCAATAAAATCCCTAAGCATTTGTTTCAGGGTTATTTGAATATCTATAACAACTA
+MISEQ:1:1101:14454:2872#ATATCGTATCTTTCCC/2
?AAAAFFFFFFFFGGGCEFGGCCHGHHFDFHHGHGHHHBGDEDFGHHHHHHHHGHGFHHHHHGHHHHHHHFHEGGFHFHHHFFHGHHHGHFHFFHEFHHHHHHH4DFHFHHGGGHCHGHHFHHH3GFHGHFFFGGFGGGFFGHHHGGGHHHHHHHHHHF2F2<2@GGCCGGEHFGHGHBHFD.FGGHGFCFG/G0GGH0<0GGHHF/CGFCGFHHHBC0CHFCF:CGGGFBFGG0BBFGGBFGEBBFGB#

@MISEQ:1:1101:16050:2871#TTGCTCGTTCTTTCCC/2
TGCACTATCAGCCGGGCCACAGCTACGCCTCGATGGGCGAAACCAAGGAAGCCGATGGCAAGAATTTCATGTCCGGCAACAAGTTCTCCAAGGACCGCATCTTCTCCAAATGGGTCATGATCCAGACCCTCGCCGTCCATCGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCGGGGTTATTCATACCAACGTGGAGACACAGAGTGACAATACCGGCGCACATAACCAACC
+MISEQ:1:1101:16050:2871#TTGCTCGTTCTTTCCC/2
>>AA>FCDFDFFGGGGGGGGFGHBFGEFGHGAAHFGFHGGGGCGHGHGHHGHGG@@EGHHHGHHHHFHHHHHHHGGCFGHGFGGHGHHHHHHGCHGEFGFFGHHHHHHHHFHHHFHHHHHBGFHHHGEEHGCGGGGGGGHHGFGHEHFDCEDGHHGC??@DEBFFACC;FF/99;990;0;09.;9EC;?############################################################

@MISEQ:1:1101:11693:2867#CGAAGTTCAACCAAAA/2
GCGGCTGCTGGCACGGAGTTAGCCGGTGCTTATTCGTTAGGTACCGTCATTATTCTTCCCTAACAAAAGGAGTTTACGCTCCGAAAAGTGTCATCCTCCACGCGGCGTTGCTGCGTCAGGGTTTCCCCCATTGCGCAATATTCCCTACTGCTGCCTCCCGTAGGAGTTTGGACCGTGTCTCAGTTCCAATGTGACTGATCATCCTCTCAGACCAGTTACGCGTCATAGCCTCGGTAGGCCGTTACCCCAC
+MISEQ:1:1101:11693:2867#CGAAGTTCAACCAAAA/2
ABAAB@DBFFFBGGGGGGAGBFGHGGEGGBGHHHGHHHHGFGGGDFGGGHHGHHHHHHHHHFHGFFHHHGHFB3FGGFCEEEGFDGG3@B@FGGGHGHHHHGGGGGGBCCF22DGADDGFH0?EFGHHGGHHHGGGGGDHGBHHHFFHHHHBGFFHHGGGHGDBGFCFFGGFFFFDEFFFGGGFBFFGFBFGGGFFFFBFFFEBFFFBBF/BEBFFFFBEDFB@D.FBBFBFD?AE.:B9BDDFAB/ADA
)";

  std::istringstream issfwd( forwardReadsContent );
  std::istringstream issrev( reverseReadsContent );
  std::ostringstream os;

  Reader< DNA > reader( issfwd, issrev );
  Merger< DNA > merger;

  FASTQ::Writer< DNA > writer( os );
  Sequence< DNA >      fwd, rev;

  while( reader.Read( &fwd, &rev ) ) {
    Sequence< DNA > merged;

    if( merger.Merge( fwd, rev, &merged ) ) {
      writer << merged;
    }
  }

  // usearch output for nonstaggered
  const char* expectedOutput = R"(@MISEQ:1:1101:14454:2872#ATATCGTATCTTTCCC/1
CATTAGGGTTAGCCTCGGTACGGTCAGGCATCCACGGCGCTTTAAAATAGTTGTTATAGATATTCAAATAACCCTGAAACAAATGCTTAGGGATTTTATTGGTATCAGGGTTAATCGTGCCAAGAAAAGCGGCATGGTCAATATAACCAGTAGTGTTAACAGTCGGGAGAGGAGTGGCATTAACACCATCCTTCATGAACTTAATCCACTGTTCACCATAAACGTGACGATGAGGGACATAAAAAGTAAAAATGTCTACAGTAGAGTCAATAGCAAGGCCACGACGCAATGGAGAAA
+
1>AA1@FFFF@1BGBGGGEFE?EFEAG0FGGHGFHFGGGGGGGHEHGJKK6KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKEKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKHHGFDEDGBHHHGHGHHFDFHHGHCCGGFECGGGFFFFFFFFAAAA?
@MISEQ:1:1101:16050:2871#TTGCTCGTTCTTTCCC/1
CGATGGACGGCGAGGGTCTGGATCATGACCCATTTGGAGAAGATGCGGTCCTTGGAGAACTTGTTGCCGGACATGAAATTCTTGCCATCGGCTTCCTTGGTTTCGCCCATCGAGGCGTAGCTGTGGCCCGGCTGATAGTGCA
+
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
)";

  REQUIRE( os.str() == expectedOutput );
}
